/* ============================================================
 * LudoApp core/data.js
 * Banco de preguntas local modelado EXACTAMENTE como tablas
 * relacionales (courses, categories, difficulties, questions)
 * para migración futura a PostgreSQL/Supabase/Firebase sin
 * reestructurar la lógica.
 * ============================================================ */
window.App = window.App || {};
App.seedData = (function () {
  const courses = [
    { id: 'cur_ing', nombre: 'Introducción a la Ingeniería Empresarial', descripcion: 'Inventos históricos que transformaron la ingeniería (Unidad 1).' }
  ];

  const categories = [
    { id: 'cat_ant', course_id: 'cur_ing', nombre: 'Antigüedad y Mecánica' },
    { id: 'cat_industrial', course_id: 'cur_ing', nombre: 'Revolución Industrial' },
    { id: 'cat_comunicaciones', course_id: 'cur_ing', nombre: 'Comunicaciones y Datos' },
    { id: 'cat_electricidad', course_id: 'cur_ing', nombre: 'Electrificación y Energía' },
    { id: 'cat_semiconductores', course_id: 'cur_ing', nombre: 'Semiconductores y Computación' },
    { id: 'cat_procesos', course_id: 'cur_ing', nombre: 'Procesos, Materiales y Bioprocesos' },
    { id: 'cat_empresarial', course_id: 'cur_ing', nombre: 'Ingeniería Empresarial y Futuro' }
  ];

  const difficulties = [
    { id: 'dif_facil', nombre: 'Fácil', peso_puntos: 1 },
    { id: 'dif_media', nombre: 'Media', peso_puntos: 2 },
    { id: 'dif_dificil', nombre: 'Difícil', peso_puntos: 3 }
  ];

  /* cuentas de prueba LOCALES: el docente crea la sala y comparte el
     código; los alumnos entran con su cuenta de estudiante y se unen. */
  const users = [
    { usuario: 'profe', clave: '1234', rol: 'docente', nombre: 'Prof. Ana López' },
    { usuario: 'maria', clave: '1234', rol: 'estudiante', nombre: 'María Torres' },
    { usuario: 'juan', clave: '1234', rol: 'estudiante', nombre: 'Juan Pérez' },
    { usuario: 'sofia', clave: '1234', rol: 'estudiante', nombre: 'Sofía Rojas' },
    { usuario: 'carlos', clave: '1234', rol: 'estudiante', nombre: 'Carlos Díaz' }
  ];

  /* formato pregunta (FKs + enunciado + opciones[] + respuesta_correcta)
     respuesta_correcta = índice (0-3) de la opción válida */
  const questions = [
    { id: 'q01', course_id: 'cur_ing', category_id: 'cat_ant', difficulty_id: 'dif_facil',
      enunciado: '¿Qué invento redujo drásticamente el rozamiento permitiendo transportar cargas pesadas con menor esfuerzo energético?',
      opciones: ['La rueda y el eje', 'El reloj mecánico', 'La palanca simple', 'La polea fija'],
      respuesta_correcta: 0,
      feedback: 'La rueda introdujo la transformación del movimiento y la reducción de fricción, base de la mecánica.',
      ejemplo_aplicado: 'En la ingeniería empresarial equivale a reducir cuellos de botella para optimizar el flujo de un proceso.' },
    { id: 'q02', course_id: 'cur_ing', category_id: 'cat_ant', difficulty_id: 'dif_facil',
      enunciado: '¿Qué principio físico clave aplicaron los acueductos romanos para transportar el agua por gravedad?',
      opciones: ['La pendiente constante del canal', 'El uso de bombas hidráulicas', 'La presión del vapor', 'La flotación de los caudales'],
      respuesta_correcta: 0,
      feedback: 'Los romanos dominaron la pendiente por gravedad y el arco de medio punto para estabilidad estructural.',
      ejemplo_aplicado: 'Hoy se replica en sistemas modernos de saneamiento urbano y distribución de agua potable.' },
    { id: 'q03', course_id: 'cur_ing', category_id: 'cat_ant', difficulty_id: 'dif_facil',
      enunciado: '¿Qué instrumento permitió orientarse en mar abierto sin depender de las estrellas?',
      opciones: ['La brújula magnética', 'El astrolabio solar', 'El cronómetro marino', 'La veleta'],
      respuesta_correcta: 0,
      feedback: 'La brújula usó el magnetismo terrestre para abrir rutas comerciales transoceánicas sostenidas.',
      ejemplo_aplicado: 'Conceptualmente es el ancestro del GPS y la logística satelital de flotas.' },
    { id: 'q04', course_id: 'cur_ing', category_id: 'cat_ant', difficulty_id: 'dif_facil',
      enunciado: '¿Cuál es la unidad básica de información en los sistemas de cómputo actuales?',
      opciones: ['El bit (0 y 1)', 'El byte octal', 'El pulso eléctrico continuo', 'La señal analógica'],
      respuesta_correcta: 0,
      feedback: 'El bit es la unidad binaria que sustenta toda la informática moderna.',
      ejemplo_aplicado: 'Protocolos de comunicación y almacenamiento digital trabajan sobre secuencias de bits.' },
    { id: 'q05', course_id: 'cur_ing', category_id: 'cat_industrial', difficulty_id: 'dif_facil',
      enunciado: '¿Qué tecnología de 1440 estandarizó la producción masiva de libros?',
      opciones: ['La imprenta de tipos móviles de Gutenberg', 'El papiro egipcio', 'La litografía a color', 'La fotocopiadora'],
      respuesta_correcta: 0,
      feedback: 'Sustituyó la copia manual por un proceso modular y replicable de producción bibliográfica masiva.',
      ejemplo_aplicado: 'Antecedente directo del software modular y los sistemas ERP en las empresas.' },
    { id: 'q06', course_id: 'cur_ing', category_id: 'cat_industrial', difficulty_id: 'dif_media',
      enunciado: '¿Quién transformó la energía térmica en trabajo mecánico añadiendo un condensador separado a la máquina de vapor?',
      opciones: ['James Watt', 'Thomas Edison', 'James Hargreaves', 'Isambard Brunel'],
      respuesta_correcta: 0,
      feedback: 'Watt mejoró la eficiencia del vapor, independizando la producción de los ríos.',
      ejemplo_aplicado: 'Antecedente de la automatización de plantas térmicas y la conversión de energía.' },
    { id: 'q07', course_id: 'cur_ing', category_id: 'cat_industrial', difficulty_id: 'dif_media',
      enunciado: '¿Cómo revolucionó Henry Ford el flujo de procesos industriales en 1913?',
      opciones: ['Llevó el trabajo al operario en una línea de ensamblaje móvil', 'Inventó la búsqueda en cadena', 'Creó el primer robot industrial', 'Estandarizó el vapor de alta presión'],
      respuesta_correcta: 0,
      feedback: 'Redujo tiempos de ciclo, eliminó desplazamientos y dividió el trabajo de forma especializada.',
      ejemplo_aplicado: 'Base de las metodologías Lean Manufacturing y las líneas automatizadas.' },
    { id: 'q08', course_id: 'cur_ing', category_id: 'cat_comunicaciones', difficulty_id: 'dif_facil',
      enunciado: '¿Qué sistema codificó los mensajes en impulsos eléctricos discretos (Código Morse)?',
      opciones: ['El telégrafo eléctrico', 'La radio de amplitud modulada', 'El fax óptico', 'El teléfono de baquelita'],
      respuesta_correcta: 0,
      feedback: 'Fue el primer sistema de transmisión digital a distancia mediante circuitos eléctricos.',
      ejemplo_aplicado: 'Fundamento de los protocolos binarios de las redes de telecomunicación.' },
    { id: 'q09', course_id: 'cur_ing', category_id: 'cat_comunicaciones', difficulty_id: 'dif_media',
      enunciado: '¿Qué principio del telégrafo se considera el antecesor de las redes de datos digitales?',
      opciones: ['Enviar información codificada a distancia por impulsos discretos', 'La transmisión de voz analógica', 'El almacenamiento en cintas magnéticas', 'La modulación de señales de radio FM'],
      respuesta_correcta: 0,
      feedback: 'Demostró que la información puede codificarse y transmitirse de forma discreta a distancia.',
      ejemplo_aplicado: 'Los 0s y 1s de las redes modernas heredan ese principio.' },
    { id: 'q10', course_id: 'cur_ing', category_id: 'cat_electricidad', difficulty_id: 'dif_media',
      enunciado: '¿Qué ventaja tuvo la corriente alterna de Tesla sobre la corriente continua de Edison?',
      opciones: ['Transportar energía a altas tensiones y largas distancias con menos pérdidas', 'Ser más barata de generar en pilas', 'No requerir cables de transmisión', 'Almacenarse en baterías de plomo'],
      respuesta_correcta: 0,
      feedback: 'La CA escala los sistemas eléctricos a nivel regional y nacional.',
      ejemplo_aplicado: 'Suministro eléctrico ininterrumpido para parques industriales y datacenters.' },
    { id: 'q11', course_id: 'cur_ing', category_id: 'cat_electricidad', difficulty_id: 'dif_media',
      enunciado: '¿Cómo convierte una célula fotovoltaica la radiación solar en electricidad?',
      opciones: ['Por el efecto fotoeléctrico, sin emisiones contaminantes en sitio', 'Quemando combustible fósil', 'Por inducción electromagnética térmica', 'Almacenando luz en baterías de corriente alterna'],
      respuesta_correcta: 0,
      feedback: 'Aprovecha directamente una fuente limpia e inagotable.',
      ejemplo_aplicado: 'Estrategias de descarbonización e independencia energética en plantas industriales.' },
    { id: 'q12', course_id: 'cur_ing', category_id: 'cat_electricidad', difficulty_id: 'dif_dificil',
      enunciado: '¿Por qué la pila voltaica (1800) fue crucial para la ciencia y la ingeniería?',
      opciones: ['Fue la primera fuente continua y estable de corriente eléctrica', 'Fue el primer acumulador de agua', 'Inventó el electroimán industrial', 'Generó electricidad sin reacción química'],
      respuesta_correcta: 0,
      feedback: 'Superó las descargas estáticas momentáneas, permitiendo experimentar con corriente constante.',
      ejemplo_aplicado: 'Antecedente de las baterías de litio para vehículos eléctricos y renovables.' },
    { id: 'q13', course_id: 'cur_ing', category_id: 'cat_semiconductores', difficulty_id: 'dif_facil',
      enunciado: '¿Qué componente de estado sólido (1947, Laboratorios Bell) reemplazó a los tubos de vacío?',
      opciones: ['El transistor', 'El condensador cerámico', 'El relé electromecánico', 'El diodo de neón'],
      respuesta_correcta: 0,
      feedback: 'Amplifica y conmuta señales con alto rendimiento y menor tamaño/consumo.',
      ejemplo_aplicado: 'Miles de millones de micro-conmutadores están hoy en cada chip.' },
    { id: 'q14', course_id: 'cur_ing', category_id: 'cat_semiconductores', difficulty_id: 'dif_media',
      enunciado: '¿Qué aportó el concepto de la "Máquina Universal" de Alan Turing a la informática?',
      opciones: ['Una sola máquina podía ejecutar cualquier algoritmo cambiando sus instrucciones', 'El primer ordenador con ratón', 'La transmisión de datos por fibra óptica', 'El cálculo manual de logaritmos'],
      respuesta_correcta: 0,
      feedback: 'Es el origen del programa almacenado y del software flexible.',
      ejemplo_aplicado: 'Base de la Inteligencia Artificial y la automatización de procesos (RPA).' },
    { id: 'q15', course_id: 'cur_ing', category_id: 'cat_semiconductores', difficulty_id: 'dif_dificil',
      enunciado: '¿Qué integró el microprocesador Intel 4004 por primera vez en un solo circuito?',
      opciones: ['La CPU completa en un único chip', 'La memoria RAM y el teclado', 'La tarjeta de video', 'El módem telefónico'],
      respuesta_correcta: 0,
      feedback: 'Fue el paso decisivo para incorporar poder de cómputo en cualquier maquinaria.',
      ejemplo_aplicado: 'Los PLC que operan brazos robóticos en fábricas descienden de ese concepto.' },
    { id: 'q16', course_id: 'cur_ing', category_id: 'cat_procesos', difficulty_id: 'dif_media',
      enunciado: '¿Qué combinación de materiales hizo del hormigón armado un material revolucionario?',
      opciones: ['Concreto a compresión + acero a tracción', 'Vidrio templado + madera', 'Aluminio + cobre fundido', 'Cerámica + plomo'],
      respuesta_correcta: 0,
      feedback: 'Aprovecha propiedades mecánicas complementarias de dos materiales.',
      ejemplo_aplicado: 'Construcción de rascacielos, puentes de gran luz y megaproyectos.' },
    { id: 'q17', course_id: 'cur_ing', category_id: 'cat_procesos', difficulty_id: 'dif_media',
      enunciado: '¿Cuál es el principio de funcionamiento del radar?',
      opciones: ['Emite ondas electromagnéticas que rebotan y calculan distancia y velocidad', 'Detecta metales por gravedad', 'Fotografía en infrarrojo térmico', 'Mide la presión atmosférica'],
      respuesta_correcta: 0,
      feedback: 'Es un método de detección remota e inspección no destructiva.',
      ejemplo_aplicado: 'Sensores LiDAR en vehículos autónomos y control del tráfico aéreo.' },
    { id: 'q18', course_id: 'cur_ing', category_id: 'cat_procesos', difficulty_id: 'dif_dificil',
      enunciado: '¿Qué exigencia técnica impulsó la producción masiva de penicilina?',
      opciones: ['Biorreactores de fermentación profunda y esterilización industrial', 'Telefonía celular de alta potencia', 'Motores de combustión compactos', 'Circuitos integrados de vacío'],
      respuesta_correcta: 0,
      feedback: 'El nacimiento de la industria biotecnológica y farmacéutica moderna.',
      ejemplo_aplicado: 'Producción industrial de vacunas y enzimas de limpieza biológica.' },
    { id: 'q19', course_id: 'cur_ing', category_id: 'cat_procesos', difficulty_id: 'dif_dificil',
      enunciado: '¿Qué principio aerodinámico dominaron los Hermanos Wright para lograr el vuelo controlado?',
      opciones: ['Control de tres ejes combinado con una buena relación potencia-peso', 'Solo la sustentación de las alas fijas', 'El empuje de cohetes de pólvora', 'La flotación de dirigibles rígidos'],
      respuesta_correcta: 0,
      feedback: 'No bastó generar sustentación: había que controlar la estabilidad del sistema dinámico.',
      ejemplo_aplicado: 'Simulación de fluidos y gestión de riesgos en proyectos aeronáuticos.' },
    { id: 'q20', course_id: 'cur_ing', category_id: 'cat_comunicaciones', difficulty_id: 'dif_dificil',
      enunciado: '¿Qué aporte arquitectónico introdujo ARPANET en 1969 para la resiliencia de las redes?',
      opciones: ['Conmutación de paquetes distribuida y tolerante a fallos', 'Enlaces satelitales exclusivos', 'La transmisión de voz por circuitos cerrados', 'El almacenamiento central único de datos'],
      respuesta_correcta: 0,
      feedback: 'Los datos llegan a destino aunque un nodo falle, gracias al diseño descentralizado.',
      ejemplo_aplicado: 'Arquitectura Cloud Computing y la infraestructura global de Internet.' },
    { id: 'q21', course_id: 'cur_ing', category_id: 'cat_industrial', difficulty_id: 'dif_dificil',
      enunciado: '¿Por qué el motor de combustión interna impactó la logística y la cadena de suministro mundial?',
      opciones: ['Ofrece alta densidad de potencia y autonomía móvil para transporte pesado', 'Es más silencioso que el vapor', 'No requiere combustibles líquidos', 'Reduce la velocidad de las flotas'],
      respuesta_correcta: 0,
      feedback: 'Reemplazó al vapor por combustibles de mayor energía por unidad de masa.',
      ejemplo_aplicado: 'Cadenas de suministro Just-In-Time movidas por transporte terrestre y marítimo.' },
    { id: 'q22', course_id: 'cur_ing', category_id: 'cat_empresarial', difficulty_id: 'dif_media',
      enunciado: '¿Cómo contribuye la célula fotovoltaica al cambio de matriz energética en empresas sostenibles?',
      opciones: ['Transforma radiación solar en electricidad sin emisiones en sitio', 'Reduce solo el consumo de agua', 'Elimina la necesidad de mantenimiento', 'Convierte calor residual en frío'],
      respuesta_correcta: 0,
      feedback: 'Aprovechamiento directo de energías limpias e inagotables.',
      ejemplo_aplicado: 'Estrategias de descarbonización e independencia energética industrial.' },
    { id: 'q23', course_id: 'cur_ing', category_id: 'cat_empresarial', difficulty_id: 'dif_media',
      enunciado: '¿Qué hizo el transistor posible en términos de escala tecnológica?',
      opciones: ['Miniaturizar y reducir el consumo de los sistemas informáticos', 'Eliminar todo el cableado eléctrico', 'Conectar satélites sin antenas', 'Reemplazar la energía solar por baterías'],
      respuesta_correcta: 0,
      feedback: 'Permitió la miniaturización, reduciendo tamaño y consumo eléctrico.',
      ejemplo_aplicado: 'Laptops y smartphones actuales contienen miles de millones de transistores.' },
    { id: 'q24', course_id: 'cur_ing', category_id: 'cat_empresarial', difficulty_id: 'dif_dificil',
      enunciado: '¿Cómo se relaciona la evolución de la ingeniería (de lo mecánico a la IA) con el rol del ingeniero empresarial?',
      opciones: ['Integra tecnología, procesos y personas para crear valor en las organizaciones', 'Solo debe reparar máquinas antiguas', 'Debe ignorar la tecnología moderna', 'Se limita a vender dispositivos'],
      respuesta_correcta: 0,
      feedback: 'La visión sistémica e integradora es la esencia del ingeniero empresarial.',
      ejemplo_aplicado: 'Liderazgo en la transformación digital e innovación sostenible de las organizaciones.' }
  ];

  return { courses, categories, difficulties, questions, users };
})();